## OPV2V dataset root
dataset:
  root: D:\\Data\\dataset\\OPV2V\\train
  additional: D:\\Data\\dataset\\OPV2V\\additional\\train
  batch_size: 2
  num_workers: 2
  shuffle: True

model_save_path:


model_params:
  SCPNet:
    output_shape:
      - 256
      - 256
      - 32
    fea_dim: 7
    out_fea_dim: 256
    num_class: 20
    num_input_features: 32
    use_norm: True
    init_size: 32
  LMSCNet:
    epochs: 1000
    input_dimensions:
      - 256
      - 256
      - 32
    class_num: 23
    class_frequencies:
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1


